paypal.clientId=AUl4T93BPBjSUm2840NDGmSkKz4I2f0mQy5R0nsHUtn0pRkvc6UOMOiXOOEudfRaODYy9WTpEx64OETY
paypal.clientSecret=EFvH1IfjIAGYtVY4ocFB0KQvHY89YgPhgPK36T_2YakOw4vubZ80rBI1_xB3ZZ42-7HbtSzMzkVH1ygL
paypal.baseUrl=https://api-m.paypal.com
pv.allow-dev-origin=false 