server:
  port: 8080

stripe:
  secret-key: sk_test_51SCNUDAy1lA1oqnAg6uyk4NGe32IIhD4sP2qk2DgdpcQhbtIpDCBqzrAs70KxokhFanBhR8DAftzlWbT7RTllaYj00Qklt4SyX

qr:
  price-eur: 1000                  # 10€ in centesimi
  product-name: "QR Code PRO Sbloccato"
  allow-dev-origin: true           # abilita CORS da localhost:3000 in dev
  automatic-tax: false 