spring.config.import=optional:classpath:secrets.properties

paypal.baseUrl=https://api-m.paypal.com
paypal.clientId=${paypal.clientId}       
paypal.clientSecret=${paypal.clientSecret}

server.error.include-message=never
server.error.include-stacktrace=never
